### PR TITLE
Update victory

### PR DESCRIPTION
**Pull request by boygirl**
cc/ @chrisbolin this PR updates Victory to 0.21.0 and adds support for polar charts.

Caveats:
I couldn't figure out how to work around https://github.com/FormidableLabs/victory-native/issues/103, so I've temporarily disabled text rotations

~Spurious test failure for `VictoryLabel`~ Updated `react-native-svg-mock` to include `TSpan` mock

### CODE REVIEW

**Comment by chrisbolin** [comment]
I'm getting `Warning: Each child in an array or iterator should have a unique "key" prop.` in the demo. Trace:
ExceptionsManager.js:71 Warning: Each child in an array or iterator should have a unique "key" prop.
```
Check the render method of `_class`. See https://fb.me/react-warning-keys for more information.
    in Path (at area.js:20)
    in _class (at victory-area.js:13)
    in RNSVGGroup (at G.js:20)
    in G (at victory-clip-container.js:17)
    in RNSVGGroup (at G.js:20)
    in G (at victory-clip-container.js:15)
    in VictoryClipContainer (at victory-area.js:16)
    in VictoryArea (at demo.js:408)
    in RNSVGGroup (at G.js:20)
    in G (at victory-stack.js:12)
    in VictoryStack (at demo.js:407)
    in RNSVGSvgView (at Svg.js:80)
    in Svg (at victory-container.js:82)
    in RCTView (at View.js:128)
    in View (at victory-container.js:81)
    in VictoryContainer (at victory-chart.js:13)
    in VictoryChart (at demo.js:406)
    in RCTScrollContentView (at ScrollView.js:649)
    in RCTScrollView (at ScrollView.js:732)
    in ScrollView (at demo.js:136)
    in Demo (at renderApplication.js:35)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:93)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:92)
    in AppContainer (at renderApplication.js:34)
```

I don't _think_ that's demo-specific?

**Comment by chrisbolin** [comment]
but that could be completely unrelated to this PR

**Comment by boygirl** [comment]
cool. Travis isn't picking up my latest published versions of `react-native-svg-mock` or `victory-chart`

**Comment by boygirl** [comment]
Yay! It caught up!

**Comment by boygirl** [comment]
Working for me too now. Merging :)

**Pull request merged**
