### PR TITLE
use ~ versions

### PR DESCRIPTION
**Pull request by boygirl**
cc/ @chrisbolin

### CODE REVIEW

**Comment by boygirl** [comment]
@chrisbolin Sorry for the delay. Does this look alright to you? Especially the changes to the readme

**Comment by chrisbolin** [comment]
Approved! I really like this approach.

One thing we might consider if this is still confusing for user is to use `*` peer dependencies for `react-native-svg`. That way at least the user will see on the command line that they need the library. (the other two peer deps, react and RN, will obviously be installed)

**Comment by chrisbolin** [comment]
also: fixes https://github.com/FormidableLabs/victory-native/issues/110

**Comment by boygirl** [comment]
Lack of peerDeps in package.json is consistent with other victory repos. Let's try this out and see how many people are opening issues / confused in the gitter channel.

**Pull request merged**
