### PR TITLE
Update demo

### PR DESCRIPTION
**Pull request by ratson**
Update demo to use latest react-native

### CODE REVIEW

**Comment by boygirl** [comment]
@ratson Thanks for taking the time to update the demo. Unfortunately I can't get it to run in your branch. Can you describe the steps you use to run the demo?

After a quick look at the code, I think this issue might be that the dependencies in the root `package.json` need to be updated to match the dependencies you've updated in `demo/package.json`

**Comment by ratson** [comment]
```
cd demo
yarn
yarn react-native run-ios
```

**Comment by boygirl** [comment]
@ratson thanks for describing the steps you used to run the demo app. That does work, but there are a few issues. Prior to these changes we were running the demo from the root directory as described in the readme, and we were able to pick up changes from `/lib` without rebuilding. With this change, it looks like `victory-native` is being yarn installed, so it's not possible to pick up local changes. I don't mind changing the steps to run the demo, but being able to use the demo to see development changes is a hard requirement. Can you update this work so that 1) the demo app still picks up changes to `lib/` and 2) and changes in the steps required to run the demo app are described in `README.md`?

Thank you for working on this! I really appreciate the help!

**Comment by ratson** [comment]
@boygirl Update instructions for local development, see if it works for you.

**Comment by boygirl** [comment]
@ratson I'm still not able to see changes to lib in your branch. I'm testing this by changing the render method of `lib/components/victory-primitives/tspan.js` so that it will always render the same string ("HI!"), but the labels in the demo remain unchanged. I think the alias is not working.

**Comment by ratson** [comment]
@boygirl I could see the update. Did you enable hot reload for test? I add `--reset-cache` to start the server, see if it helps.

**Comment by boygirl** [comment]
@ratson yes, it works! Thank you so much for the help!

**Pull request merged**
