### PR TITLE
don't be so strict on react-native peer dep

### PR DESCRIPTION
**Pull request by chrisbolin**

### CODE REVIEW

**Comment by jevakallio** [comment]
LGTM!

**Comment by chrisbolin** [comment]
but this won't help us with create-react-native-app, as it produces package.json with `"react-native": "^0.43.4"`

**Comment by chrisbolin** [comment]
in fact, because `react-native` is pre-1.0.0, `~` and `^` are equivalent. TIL.

**Comment by chrisbolin** [comment]
so we have a choice...
A. show a Peer Dep error to everyone using RN `0.43` (including everyone using CRNA / Expo now) [what we're doing now]
B. upgrade the our peer dep to `^0.43.0` and exclude any users with older versions
C. change our deep dep to `>=0.42.0`

I prefer B. What do you think @boygirl @jevakallio ?

**Comment by chrisbolin** [comment]
@jevakallio signed off on the updates via slack :P

**Pull request merged**
