### PR TITLE
upgrade demo to react-native rn42 and react-native-svg 5.1.5

### PR DESCRIPTION
**Pull request by sibelius**
I just had some warnings

image
image

related to https://github.com/FormidableLabs/victory-native/issues/53

### CODE REVIEW

**Comment by chrisbolin** [comment]
thanks @sibelius! I'll check it out now

**Comment by chrisbolin** [comment]
Alright, the demo works for me! I can take it from here. I think I'll remove some of the `react-native` default boilerplate to keep it light.

And now I should address that `Warning: Failed prop type` issue :P @sibelius, do you get a visible warning when running the demo?

> Warning: failed prop type: Invalid prop `pointerEvents` of type `string` supplied to `Path`, expected `function`. ...

screen shot 2017-03-10 at 10 51 32 pm
screen shot 2017-03-10 at 10 52 10 pm

**Comment by chrisbolin** [comment]
@boygirl do you know if that prop type warning ^ is new? I didn't see any issues with it.

**Comment by chrisbolin** [comment]
thanks again for your help, @sibelius! I've built on your commit and will track it in https://github.com/FormidableLabs/victory-native/pull/55

**Comment by akonwi** [comment]
I'm also seeing these warnings. Is there a solution yet? 

Also, tooltip text isn't visible if the string does not contain a `\n` character. Should I open a separate issue for that?

**Comment by chrisbolin** [comment]
@akonwi we are working on releasing `0.7.0` which will fix this. I'll ping you when we do (should be in the next few days). Sorry about that!

**Comment by chrisbolin** [comment]
@akonwi and yes, please file a tooltip issue. thanks so much!

**Pull request closed without merging**
