### PR TITLE
Hide cursor in VictoryCursorContainer on touch end

### PR DESCRIPTION
**Pull request by svenlombaert**
Fixes https://github.com/FormidableLabs/victory-native/issues/349#issuecomment-430391540

### CODE REVIEW

**Comment by svenlombaert** [comment]
Let me know if I should add this part to the CursorHelpers or if it's good in this spot.

**Comment by boygirl** [comment]
@svenlombaert I do think it would be a bit cleaner in `CursorHelpers` if you don't mind. I'll get a release out for you quickly in the main Victory repo so you won't be held up.

**Comment by svenlombaert** [comment]
@boygirl Allright! Just opened a PR in the main Victory repo: https://github.com/FormidableLabs/victory/pull/1149

**Comment by boygirl** [comment]
🚀 Thanks!

**Pull request merged**
