### PR TITLE
React Native 60 upgrade

### PR DESCRIPTION
**Pull request by carlos-kelly**
The goal is to bring our native and React dependencies in line with latest versions. React Native 60 requires the Android project use AndroidX support libraries and we can opt into Hermes. We have done both for our Android project in this case. iOS does not have any major architectural changes like Android. Finally this simplifies some of the dev deps in the JS project.

Screen Shot 2019-07-31 at 4 39 53 PM
Screen Shot 2019-07-31 at 4 39 57 PM

### CODE REVIEW

**Comment by boygirl** [comment]
@carlos-kelly this is throwing the following error in the iOS simulator:
Screen Shot 2019-07-31 at 4 32 47 PM

Are you seeing this as well?

**Comment by carlos-kelly** [comment]
@boygirl When I upgraded I had to call the unlink then relink commands for native deps. 

```
react-native unlink react-native-gesture-handler
react-native unlink react-native-svg
react-native link react-native-gesture-handler
react-native link react-native-svg
```
That should not be happening on a fresh clone.

**Comment by carlos-kelly** [comment]
I just cloned this project fresh in a new dir, changed to this branch, yarn'd in both dirs, and ran the iOS demo and it came up fine with extra commands. My guess would be derived data or caching, but I'd love to narrow it down.

**Comment by boygirl** [comment]
Yep! I tried with a fresh clone, and all is well. Looks good!

**Pull request merged**
